<a href="https://colab.research.google.com/github/nguyenhieuec/Course_18_065/blob/master/Course_18_065_Lesson_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This notebook is try to give you a sense of math in python. This notebook is follow along with [Course 18.065 by Professor Strang](https://www.youtube.com/watch?v=Cx5Z-OslNWE)
</br >Usage tips:
1. You can use any programming language as you wish to follow the video guide.
2. Feel the math ideas behind it. Not the code.

@Author : Hieu Nguyen Vu Trung. Email: hieu.nguyen2018@qcf.jvn.edu.vn

1. Create a matrix A

In [24]:
import numpy as np
# import matplotlib.pyplot as plt
# import scipy as sp
# from scipy.linalg import lu
# from mpl_toolkits.mplot3d import Axes3D
# %matplotlib inline


A = np.matrix([[2,1,3],[3,1,4],[5,7,12]])
print(A)
print(type(A))

[[ 2  1  3]
 [ 3  1  4]
 [ 5  7 12]]
<class 'numpy.matrix'>


At this point you got matrix A, but the computer can not have a undefine variable likes ${x_{1}}$,${x_{2}}$, $x_3$ etc so to demo I wll take the closet way to present $x$ variable so we'll get a random $x$ for each time we run the cell.

$\left[ \begin{array}{ccc}{2} & {1} & {3} \\ {3} & {1} & {4} \\ {5} & {7} & {12}\end{array}\right] \left[ \begin{array}{l}{x_{1}} \\ {x_{2}} \\ {x_{3}}\end{array}\right]$

In [28]:
# Set a seed to easy to follow.
np.random.seed(2019) 
X = np.matrix(np.random.randint(10,size=(3,1)))
print(X)

[[8]
 [2]
 [5]]


So we have the column space is $C(A)$ that is 
$C(A_{1})$, and $C(A_{2})$ cause when we sum the first two column we get $C(A_{3})$ so that this column is not independent.

In [29]:
print(A[:,0])
print(A[:,1])

print(A[:,0] + A[:,1])

[[2]
 [3]
 [5]]
[[1]
 [1]
 [7]]
[[ 3]
 [ 4]
 [12]]


In fact we all do dot product in This way. $A$ rows dot product with $X$

So please keep this idea in mind before we move on. We now see it as a Vector-wise like this one.
</br>
$x_{1} \left[ \begin{array}{l}{2} \\ {3} \\ {5}\end{array}\right]+ x_{2} \left[ \begin{array}{l}{1} \\ {1} \\ {7}\end{array}\right]+x_{3} \left[\begin{array}{l}{3} \\ {4} \\ {12}\end{array}\right]$
</br>


In [39]:
print(A.dot(X)) # Normal way

# This will help you know about take a value out of the matrix

print(A[0,0]*X[0] + A[0,1]*X[1] + A[0,2]*X[2])
print(A[1,0]*X[0] + A[1,1]*X[1] + A[1,2]*X[2])
print(A[2,0]*X[0] + A[2,1]*X[1] + A[2,2]*X[2])

[[ 33]
 [ 46]
 [114]]
[[33]]
[[46]]
[[114]]


Rank of matrix.

Noted: this a matrix present a line in $R^{3}$ space

$\left[ \begin{array}{ccc}{1} & {3} & {8} \\ {1} & {3} & {8} \\ {1} & {3} & {8}\end{array}\right] $ = $\left[ \begin{array}{l}{1} \\ {1} \\ {1}\end{array}\right] \left[ \begin{array}{ccc}{1} & {3} & {8} \end{array}\right]$

In [3]:
B = np.matrix([[1,3,8],[1,3,8],[1,3,8]])

np.linalg.matrix_rank(B)

1

Now you know that the $C(A)$ (column space) is a plane and the basis literarily is a set of column which independent in the column space.

Consider the matrix A:

$\left[ \begin{array}{ccc}{2} & {1} & {3} \\ {3} & {1} & {4} \\ {5} & {7} & {12}\end{array}\right] $

We have two independent column is 

$\left[ \begin{array}{cc}{2} & {1}  \\ {3} & {1} \\ {5} & {7} \end{array}\right] $ 

In [33]:
C = indA = A[:,[0,1]]
print(indA)

[[2 1]
 [3 1]
 [5 7]]


The number of independent column also is the rank of the matrix

In [34]:
np.linalg.matrix_rank(A)

2

Now we come to matrix factorization. 

$\left[ \begin{array}{ccc}{2} & {1} & {3} \\ {3} & {1} & {4} \\ {5} & {7} & {12}\end{array}\right] $ =  $\left[ \begin{array}{cc}{2} & {1}  \\ {3} & {1} \\ {5} & {7} \end{array}\right] $ x $\left[ \begin{array}{cc}{1} & {0} & {1} \\ {0} & {1} & {1}\end{array}\right]$

This is the form of $A = C \cdot R $

$C$ is the matrix with 2 independent column 3 rows, we have a $C(m,n)$ with $m$ is a rows and $m = 3$, $n = 2$ so $C(3,2)$ we need multiply $C$ with matrix $R(2,3)$ to get back matrix $A(3,3)$



Noted: In case you don't know why google with keyword " matrix multiplication "

In [39]:
R = np.matrix([[1,0,1],[0,1,1]])
print(R)

[[1 0 1]
 [0 1 1]]


Now we have $C$ is a basis for the column space and $R$ is basis for the row space.

The row space is equal to the transpose of column space $C(A^{T})$. 

We can check the basis by definition of it:


*   $R$ is linearly independent.
*   $ R$ is a spanning set. (like the prof said, this mean the combination of vector in $R$ is all the rows in $A$)



In [38]:
print(C[0,:])
print(C[0,:].dot(R))

[[2 1]]
[[2 1 3]]


Noted: The column space of the matrix has another name is the range of the matrix.

Random sampling matrix. 

$Ax$ with $x$ is a random matrix $x(m,1)$  so $Ax$ is in column space.

In [0]:
# This still not working yet but the idea is it.
# def samplingmatrix(A,n,rangeRnd=10):
#   """input @param n: The number column of the matrix output
#            @param A: The base matrix to sampling. 
#            @param rangeRnd: the range of random function take in. @Default is 10
#      local @param x: random matrix x(m,1) with m rows and 1 column 
#            @param m: number of row of matrix
#            @param matrix: output matrix
#      output: The sample matrix follow the lecture.
#   """
#   m = A.shape[0]
#   B = []
  
#   for i in range(0,n):
#     x = np.matrix(np.random.randint(rangeRnd,size=(m,1)))
#     tmp = np.matrix(A.dot(x))
#     print(tmp)
#     print(tmp.shape,B.shape)
#     np.hstack((B,tmp))
#     print(B)
#   return B

The rest are about matrix mutiplication and math idea I will updated if I have a idea I can code :D.